App\Entity\Book:
    properties:
        name:
            - NotBlank: ~
        authors:
            - Count:
                  min: 1

App\Entity\Author:
    properties:
        name:
            - NotBlank: ~
